import { ArrowLeft, ExternalLink, Link2, X } from 'lucide-react';
import { Button } from '../../../shared/components/ui/button';
import { NoteContent } from '../../notes/components/NoteContent';
import { useGetNote } from '../../notes/hooks/useNotes';
import type { Note } from '../../notes/types/note.types';

export function QuickNoteDetail({note, onBack, onClose, onOpenFull}: {note: Note; onBack: () => void; onClose: () => void; onOpenFull: () => void}) {
  const detail = useGetNote(note.id);
  const html = detail.data?.contentHtml ?? note.contentHtml;
  return <main className="h-screen overflow-hidden bg-[#f7f8fc] p-3"><section className="flex h-full min-h-0 flex-col overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="window-drag flex h-16 shrink-0 items-center border-b px-4"><button onClick={onBack} className="window-no-drag rounded-lg border-0 bg-transparent p-2 text-muted-foreground hover:bg-muted" aria-label="Back"><ArrowLeft size={18}/></button><div className="ml-2 min-w-0"><p className="m-0 text-xs text-muted-foreground">Quick detail</p><strong className="block truncate text-sm">{note.title}</strong></div><button onClick={onClose} className="window-no-drag ml-auto rounded-lg border-0 bg-transparent p-2 text-muted-foreground hover:bg-muted" aria-label="Close"><X size={17}/></button></header><div className="scrollbar min-h-0 flex-1 overflow-y-auto p-6"><span className="rounded-full px-2.5 py-1 text-xs font-semibold" style={{background: `${note.categoryColor}14`, color: note.categoryColor}}>{note.category}{note.categoryIds.length > 1 && ` +${note.categoryIds.length - 1}`}</span><h1 className="mb-2 mt-4 text-2xl leading-tight">{note.title}</h1><p className="m-0 text-xs text-muted-foreground">Updated {note.updatedAt}</p><div className="my-5 h-px bg-border"/>{html ? <NoteContent html={html} searchQuery="" activeIndex={0} onMatchCountChange={() => {}} onActiveIndexChange={() => {}} onWideTableChange={() => {}} inline chrome={false} /> : <p className="whitespace-pre-wrap text-sm leading-7 text-slate-600">{note.content}</p>}{!!note.relatedIds.length && <div className="mt-6 flex items-center gap-2 rounded-xl bg-muted/60 p-3 text-xs text-muted-foreground"><Link2 size={15}/>{note.relatedIds.length} related {note.relatedIds.length === 1 ? 'memory' : 'memories'}</div>}</div><footer className="flex h-14 shrink-0 items-center border-t bg-muted/30 px-5"><span className="text-[11px] text-muted-foreground">Esc back</span><Button size="sm" className="ml-auto" onClick={onOpenFull}>Open full app <ExternalLink size={14}/></Button></footer></section></main>;
}
